### ISSUE TITLE
ListBox数据绑定无法实现动态的切换

### ISSUE THREAD

**Issue by qq775862807** [DingpingZhang/WpfExtensions#1]
你好，我想问一下，在项目的cs代码中设置的值（ListBox数据绑定）可以进行动态更新吗？使用I18nManager.Instance.Get(key)只能重新加载后会变更语言显示，无法实现动态的切换

**Comment by qq775862807** [comment]
在Dotnet9的提示下，最终的解决方法是 在vm里注册国际化变化事件，在事件里更新后台绑定的数据实现

**Comment by DingpingZhang** [comment]
1. 不推荐在 C# 代码里做国际化；
2. 如果一定要，则使用 I18nSource 代替 string 类型，然后通过 I18nSource.Value 访问文本，同时，绑定到 UI 上也是 {Binding I18nSource.Value}，markup I18n 也是帮你自动创建这个实例的；
3. 它的原理仍然是事件通知，只不过 WPF 会自动订阅这个事件，而你的 VM 要靠你手动订阅。
