### ISSUE TITLE
Use ifExtension alongside localization

### ISSUE THREAD

**Issue by ghost1372** [DingpingZhang/WpfExtensions#2]
Hi, I am using Resx file to localize the program, It seems that ifExtension cannot use this type

```
<Button Content="{mx:If {Binding boolProperty},
                            {hc:Localization data},
                            {hc:Localization anotherdata}}" />
```
And I get a NullReferenceException error

**Comment by DingpingZhang** [comment]
What is the `{hc:Localization}` markup? I need more details to debug.

**Comment by ghost1372** [comment]
> What is the `{hc:Localization}` markup? I need more details to debug.

see here
https://github.com/ghost1372/HandyControls/blob/develop/src/Shared/HandyControl_Shared/HandyControls/DynamicLanguage/Extensions/LocalizationExtension.cs

**Comment by DingpingZhang** [comment]
If you want to use i18n text, you can use `{markup:I18n}` markup in this project.
You can refer to the demo of this project, and it work well.
