### ISSUE TITLE
搭配Prism 8時，無法正常透過綁定屬性使用

### ISSUE THREAD

**Issue by jaelys** [DingpingZhang/WpfExtensions#3]
例如：
`<Button` Command="{markup:If {Binding BoolProperty},
                            {Binding OkCommand},
                            {Binding CancelCommand}}" `/>`
                            
 BoolProperty這個屬性，在使用Prism 8 MVVM時，所有依靠屬性判斷的擴充功能皆失效，請問如何解決比較好?

**Comment by DingpingZhang** [comment]
请提供一个最小可复现的 demo。
BoolProperty 在变更时，需要触发 `PorpertyChanged` 事件，也就是用 Prism 里的 `SetProperty(ref field, value)`。

**Comment by jaelys** [comment]
是的屬性都是SetProperty(ref field, value)設置的，WPF本身都能正常使用，
但只要用到markup:If 、markup:Switch、markup:I18nString之類的，就是無法正常
我準備一個可以實現的Demo，我找時間處理，感謝您

**Comment by DingpingZhang** [comment]
@jaelys Hi，Demo 有进展吗？

**Comment by jaelys** [comment]
抱歉一直忙碌中，遺忘了此事，今天補上Demo
[WpfExtensionsDemo.zip](https://github.com/DingpingZhang/WpfExtensions/files/7215996/WpfExtensionsDemo.zip)
只有第一次獲取屬性生效，屬性變更後，無法觸發

**Comment by DingpingZhang** [comment]
@jaelys 
额…… 事情比较尴尬：恐怕是你的拼写错误，如下图：ViewModel 中的 `OKCommand` `K` 是大写，而 Xaml 中是 `OkCommand`，`k` 变成小写了。我修改了拼写之后，一切正常。

建议你在所有的 Xaml 中都加上：`d:DataContext="{d:DesignInstance viewModels:XxxxViewModel}"`，这句将使你在 Xaml 中也可以获得对应 ViewModel 的类型提示和自动补全，这样拼写错误就可以很快发现。

![image](https://user-images.githubusercontent.com/8541016/134523082-2ec12681-37c8-4c86-b53e-bd171b33ced1.png)

**Comment by jaelys** [comment]
我犯了低級錯誤，很抱歉浪費您的時間，這個Demo是正常運行無誤的，我找時間詳細檢查一下之前的項目為何不起作用，如有進一步消息，我再反饋，感謝您的指導，我先關閉此Issue
